name = "testjob"
main = "src/index.ts"
compatibility_date = "2024-01-07"

[triggers]
crons = ["0 9 * * *"]

[[kv_namespaces]]
binding = "CRON_LOCK"
id = "4705d229a4ab40f38be5443f17e7da15"


[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true