export const location = {
  ALMULT: "Al Multaqua Ballroom",
  BUBBLE: "Bubble Lounge",
  DIC10: "Sheikh Maktoum Hall B",
  DIC2: "Sheikh Rashid Hall D",
  "DIC2-4": "Sheikh Rashid Hall C+D",
  DIC33: "Sheikh Rashid Hall E",
  DIC334: "Sheikh Rashid Hall E+F",
  DIC34: "Sheikh Rashid Hall F",
  DIC4: "Sheikh Rashid Hall C",
  DIC5: "Sheikh Rashid Hall A",
  "DIC5-6": "Sheikh Rashid Hall A+B",
  DIC6: "Sheikh Rashid Hall B",
  DIC7: "Sheikh Maktoum Hall D",
  "DIC7-9": "Sheikh Maktoum Hall A+D",
  DIC8: "Sheikh Maktoum Hall A",
  DIC810: "Sheikh Maktoum Hall B+C",
  DIC9: "Sheikh Maktoum Hall C",
  DICC: "Sheikh Rashid Hall",
  DRUM: "Sheikh Rashid Hall Drum",
  EOHAL1: "Za'abeel Hall 4",
  EOHAL2: "Za'abeel Hall 5",
  EOLNK: "Za'abeel Hall 6 3 Link",
  EOMPH1: "Za'abeel Hall 6",
  EOMPH2: "Za'abeel Hall 4 1 Link",
  HALL1: "Exhibition Hall 1",
  HALL2: "Exhibition Hall 2",
  HALL3: "Exhibition Hall 3",
  HALL4: "Exhibition Hall 4",
  HALL5: "Exhibition Hall 5",
  HALL6: "Exhibition Hall 6",
  HALL7: "Exhibition Hall 7",
  HALL8: "Exhibition Hall 8",
  HALLSM: "Sheikh Maktoum Hall",
  LBYSM: "Sheikh Maktoum Lobby",
  LINKSM: "Sheikh Maktoum Hall Link",
  LNK: "Exhibition Halls 4 + 5 Link",
  N09: "Sheikh Saeed Hall 3",
  N10: "Sheikh Saeed Hall 2",
  N11: "Sheikh Saeed Hall 1",
  N12: "Trade Centre Arena",
  N13: "Arena S1 Link",
  NH3A: "Za'abeel Hall 6 A",
  NH3B: "Za'abeel Hall 6 B",
  NH3C: "Za'abeel Hall 6 C",
  NH3D: "Za'abeel Hall 6 D",
  NH3E: "Za'abeel Hall 6 E",
  NH3F: "Za'abeel Hall 6 F",
  PAVILI: "Pavilion",
  SMFOY: "Sheikh Maktoum Hall Foyer",
  SRHABE: "Sheikh Rashid Hall A+B+E",
  SRHBAL: "Balcony inside Sheikh Rashid Hall",
  SRHCDF: "Sheikh Rashid Hall C+D+F",
  ZAB1: "Za'abeel Hall 1",
  ZAB2: "Za'abeel Hall 2",
  ZAB3: "Za'abeel Hall 3",
};
